# sudo: required

language: node_js

# services:
  # - docker

node_js:
  - "8"

script:
  - npm run lint
  - docker build -t timmyers/shtunnel-cloud .

deploy:
  on:
    branch: master
  provider: script
  skip_cleanup: true
  script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push timmyers/shtunnel
