language: node_js

node_js:
  - '8'

addons:
  ssh_known_hosts: tmye.me

script:
  - npm run lint
  - docker build -t timmyers/shtunnel-cloud .

before_deploy:
  - openssl aes-256-cbc -K $encrypted_6a9995a8e5b4_key -iv $encrypted_6a9995a8e5b4_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa

deploy:
  on:
    branch: master
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
